apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
