apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    nginx-label: nginx-daemonset
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        ssd: "true"
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
          - name: nginxstorage
            mountPath: /usr/share/nginx/html
      volumes:
      - name: nginxstorage
        hostPath: 
          path: /tmp/nginx
